//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTimeZones
    {
        public short TimeZoneID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> SunStart { get; set; }
        public Nullable<System.DateTime> SunEnd { get; set; }
        public Nullable<System.DateTime> MonStart { get; set; }
        public Nullable<System.DateTime> MonEnd { get; set; }
        public Nullable<System.DateTime> TuesStart { get; set; }
        public Nullable<System.DateTime> TuesEnd { get; set; }
        public Nullable<System.DateTime> WedStart { get; set; }
        public Nullable<System.DateTime> WedEnd { get; set; }
        public Nullable<System.DateTime> ThursStart { get; set; }
        public Nullable<System.DateTime> ThursEnd { get; set; }
        public Nullable<System.DateTime> FriStart { get; set; }
        public Nullable<System.DateTime> FriEnd { get; set; }
        public Nullable<System.DateTime> SatStart { get; set; }
        public Nullable<System.DateTime> SatEnd { get; set; }
    }
}
