//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACUnlockComb
    {
        public short UnlockCombID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Group01 { get; set; }
        public Nullable<short> Group02 { get; set; }
        public Nullable<short> Group03 { get; set; }
        public Nullable<short> Group04 { get; set; }
        public Nullable<short> Group05 { get; set; }
    }
}
