//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmLog
    {
        public int ID { get; set; }
        public string Operator { get; set; }
        public string EnrollNumber { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string MachineAlias { get; set; }
        public Nullable<int> AlarmType { get; set; }
    }
}
