//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKEXACT
    {
        public int EXACTID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public Nullable<short> ISADD { get; set; }
        public string YUYIN { get; set; }
        public Nullable<short> ISMODIFY { get; set; }
        public Nullable<short> ISDELETE { get; set; }
        public Nullable<short> INCOUNT { get; set; }
        public Nullable<short> ISCOUNT { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
