//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKINOUT
    {
        public int USERID { get; set; }
        public System.DateTime CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public Nullable<int> VERIFYCODE { get; set; }
        public string SENSORID { get; set; }
        public string Memoinfo { get; set; }
        public string WorkCode { get; set; }
        public string sn { get; set; }
        public Nullable<short> UserExtFmt { get; set; }
    }
}
