//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceTemp
    {
        public int TEMPLATEID { get; set; }
        public string USERNO { get; set; }
        public Nullable<int> SIZE { get; set; }
        public Nullable<int> pin { get; set; }
        public Nullable<int> FACEID { get; set; }
        public Nullable<int> VALID { get; set; }
        public Nullable<int> RESERVE { get; set; }
        public Nullable<int> ACTIVETIME { get; set; }
        public Nullable<int> VFCOUNT { get; set; }
        public byte[] TEMPLATE { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
