//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveClass1
    {
        public int LeaveId { get; set; }
        public string LeaveName { get; set; }
        public double MinUnit { get; set; }
        public short Unit { get; set; }
        public short RemaindProc { get; set; }
        public short RemaindCount { get; set; }
        public string ReportSymbol { get; set; }
        public double Deduct { get; set; }
        public short LeaveType { get; set; }
        public int Color { get; set; }
        public short Classify { get; set; }
        public string Calc { get; set; }
    }
}
