//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machines
    {
        public int ID { get; set; }
        public string MachineAlias { get; set; }
        public int ConnectType { get; set; }
        public string IP { get; set; }
        public Nullable<int> SerialPort { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> Baudrate { get; set; }
        public int MachineNumber { get; set; }
        public bool IsHost { get; set; }
        public bool Enabled { get; set; }
        public string CommPassword { get; set; }
        public Nullable<short> UILanguage { get; set; }
        public Nullable<short> DateFormat { get; set; }
        public Nullable<short> InOutRecordWarn { get; set; }
        public Nullable<short> Idle { get; set; }
        public Nullable<short> Voice { get; set; }
        public Nullable<short> managercount { get; set; }
        public Nullable<short> usercount { get; set; }
        public Nullable<short> fingercount { get; set; }
        public Nullable<short> SecretCount { get; set; }
        public string FirmwareVersion { get; set; }
        public string ProductType { get; set; }
        public Nullable<short> LockControl { get; set; }
        public Nullable<short> Purpose { get; set; }
        public Nullable<int> ProduceKind { get; set; }
        public string sn { get; set; }
        public string PhotoStamp { get; set; }
        public Nullable<int> IsIfChangeConfigServer2 { get; set; }
        public Nullable<int> pushver { get; set; }
        public string IsAndroid { get; set; }
    }
}
