//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchClass
    {
        public int schClassid { get; set; }
        public string schName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> LateMinutes { get; set; }
        public Nullable<int> EarlyMinutes { get; set; }
        public Nullable<int> CheckIn { get; set; }
        public Nullable<int> CheckOut { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<short> AutoBind { get; set; }
        public Nullable<System.DateTime> CheckInTime1 { get; set; }
        public Nullable<System.DateTime> CheckInTime2 { get; set; }
        public Nullable<System.DateTime> CheckOutTime1 { get; set; }
        public Nullable<System.DateTime> CheckOutTime2 { get; set; }
        public Nullable<double> WorkDay { get; set; }
        public string SensorID { get; set; }
        public Nullable<double> WorkMins { get; set; }
    }
}
