//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFT
    {
        public int SHIFTID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> USHIFTID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<short> RUNNUM { get; set; }
        public Nullable<int> SCH1 { get; set; }
        public Nullable<int> SCH2 { get; set; }
        public Nullable<int> SCH3 { get; set; }
        public Nullable<int> SCH4 { get; set; }
        public Nullable<int> SCH5 { get; set; }
        public Nullable<int> SCH6 { get; set; }
        public Nullable<int> SCH7 { get; set; }
        public Nullable<int> SCH8 { get; set; }
        public Nullable<int> SCH9 { get; set; }
        public Nullable<int> SCH10 { get; set; }
        public Nullable<int> SCH11 { get; set; }
        public Nullable<int> SCH12 { get; set; }
        public Nullable<short> CYCLE { get; set; }
        public Nullable<short> UNITS { get; set; }
    }
}
