//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSMSINFO
    {
        public int REFERENCE { get; set; }
        public string SMSID { get; set; }
        public int SMSINDEX { get; set; }
        public Nullable<int> SMSTYPE { get; set; }
        public string SMSCONTENT { get; set; }
        public string SMSSTARTTM { get; set; }
        public Nullable<int> SMSTMLENG { get; set; }
        public string GENTM { get; set; }
    }
}
