//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE
    {
        public int TEMPLATEID { get; set; }
        public int USERID { get; set; }
        public int FINGERID { get; set; }
        public byte[] TEMPLATE1 { get; set; }
        public byte[] TEMPLATE2 { get; set; }
        public byte[] BITMAPPICTURE { get; set; }
        public byte[] BITMAPPICTURE2 { get; set; }
        public byte[] BITMAPPICTURE3 { get; set; }
        public byte[] BITMAPPICTURE4 { get; set; }
        public Nullable<short> USETYPE { get; set; }
        public string EMACHINENUM { get; set; }
        public byte[] TEMPLATE11 { get; set; }
        public Nullable<short> Flag { get; set; }
        public Nullable<short> DivisionFP { get; set; }
        public byte[] TEMPLATE4 { get; set; }
        public byte[] TEMPLATE3 { get; set; }
    }
}
