//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SPEDAY
    {
        public int USERID { get; set; }
        public System.DateTime STARTSPECDAY { get; set; }
        public Nullable<System.DateTime> ENDSPECDAY { get; set; }
        public short DATEID { get; set; }
        public string YUANYING { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
