//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserACPrivilege
    {
        public int UserID { get; set; }
        public int DeviceID { get; set; }
        public Nullable<int> ACGroupID { get; set; }
        public bool IsUseGroup { get; set; }
        public Nullable<int> TimeZone1 { get; set; }
        public Nullable<int> TimeZone2 { get; set; }
        public Nullable<int> TimeZone3 { get; set; }
        public Nullable<int> verifystyle { get; set; }
    }
}
