//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERINFO
    {
        public int USERID { get; set; }
        public string Badgenumber { get; set; }
        public string SSN { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string TITLE { get; set; }
        public string PAGER { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<System.DateTime> HIREDDAY { get; set; }
        public string street { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string OPHONE { get; set; }
        public string FPHONE { get; set; }
        public Nullable<short> VERIFICATIONMETHOD { get; set; }
        public Nullable<short> DEFAULTDEPTID { get; set; }
        public Nullable<short> SECURITYFLAGS { get; set; }
        public short ATT { get; set; }
        public short INLATE { get; set; }
        public short OUTEARLY { get; set; }
        public short OVERTIME { get; set; }
        public short SEP { get; set; }
        public short HOLIDAY { get; set; }
        public string MINZU { get; set; }
        public string PASSWORD { get; set; }
        public short LUNCHDURATION { get; set; }
        public byte[] PHOTO { get; set; }
        public string mverifypass { get; set; }
        public byte[] Notes { get; set; }
        public Nullable<int> privilege { get; set; }
        public Nullable<short> InheritDeptSch { get; set; }
        public Nullable<short> InheritDeptSchClass { get; set; }
        public Nullable<short> AutoSchPlan { get; set; }
        public Nullable<int> MinAutoSchInterval { get; set; }
        public Nullable<short> RegisterOT { get; set; }
        public Nullable<short> InheritDeptRule { get; set; }
        public Nullable<short> EMPRIVILEGE { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> FaceGroup { get; set; }
        public Nullable<int> AccGroup { get; set; }
        public Nullable<int> UseAccGroupTZ { get; set; }
        public Nullable<int> VerifyCode { get; set; }
        public Nullable<int> Expires { get; set; }
        public Nullable<int> ValidCount { get; set; }
        public Nullable<System.DateTime> ValidTimeBegin { get; set; }
        public Nullable<System.DateTime> ValidTimeEnd { get; set; }
        public Nullable<int> TimeZone1 { get; set; }
        public Nullable<int> TimeZone2 { get; set; }
        public Nullable<int> TimeZone3 { get; set; }
        public Nullable<int> StateATT { get; set; }
    }
}
