//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZKAttendanceMonthStatistics
    {
        public int Id { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> PortalSite { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<decimal> YingDao { get; set; }
        public Nullable<decimal> ShiDao { get; set; }
        public Nullable<decimal> ChiDao { get; set; }
        public Nullable<decimal> ZaoTui { get; set; }
        public Nullable<decimal> KuangGong { get; set; }
        public Nullable<decimal> JiaBan { get; set; }
        public Nullable<decimal> WaiChu { get; set; }
        public Nullable<decimal> YinGongWaiChu { get; set; }
        public Nullable<decimal> GongZuoShiJian { get; set; }
        public Nullable<decimal> YingQian { get; set; }
        public Nullable<decimal> QianDao { get; set; }
        public Nullable<decimal> QianTui { get; set; }
        public Nullable<decimal> WeiQianDao { get; set; }
        public Nullable<decimal> WeiQianTui { get; set; }
        public Nullable<decimal> QingJia { get; set; }
        public Nullable<decimal> PingRi { get; set; }
        public Nullable<decimal> ZhouMo { get; set; }
        public Nullable<decimal> JieJiaRi { get; set; }
        public Nullable<decimal> ChuQinShiJian { get; set; }
        public Nullable<decimal> PingRiJiaBan { get; set; }
        public Nullable<decimal> ZhouMoJiaBan { get; set; }
        public Nullable<decimal> JieJiaRiJiaBan { get; set; }
    }
}
